export const SAVE_PEOPLE_DATA = 'SAVE_PEOPLE_DATA';
export const SAVE_PLANETS_DATA = 'SAVE_PLANETS_DATA';
export const SAVE_FILMS_DATA = 'SAVE_FILMS_DATA';
export const SAVE_VEHICLES_DATA = 'SAVE_VEHICLES_DATA';
export const SAVE_STARSHIPS_DATA = 'SAVE_STARSHIPS_DATA';
export const SAVE_SPECIES_DATA = 'SAVE_SPECIES_DATA';
export const ERROR = 'ERROR';


